### ISSUE TITLE
New translation: pt-BR

### ISSUE THREAD

**Issue by feamcor** [ferrous-systems/rust-three-days-course#148]
Hi, I forked your repo, created a `pt-BR` branch, and I'm slowly translating it to [Brazilian Portuguese](https://en.wikipedia.org/wiki/Brazilian_Portuguese), which should cover for all [Lusophones](https://en.wikipedia.org/wiki/Lusophone). Could you please advise for the dependencies and tools needed for a local run? For instance, I saw that `pandoc` was needed. What about the Bower-related files? Which local web server you use for the static content? Thank you.

**Comment by skade** [comment]
Hi, you don't need to run anything locally. The only place where you need pandoc is to turn the table of contents into html.

You can use any webserver that just serves static content.

**Comment by feamcor** [comment]
Thanks.

**Comment by skade** [comment]
Happy to :). Please keep in mind that the course is fast evolving and we currently don't have a good setup to track i18n, but I'd love to improve there.

Please feel free to ask any questions.
